# Generated by Django 2.2.2 on 2019-06-12 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
