# Generated by Django 2.2.2 on 2019-06-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20190617_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe_image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
    ]
