# Generated by Django 2.2.2 on 2019-06-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_post_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recipe_image',
            new_name='model_pic',
        ),
    ]
