# Generated by Django 2.2.2 on 2019-06-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20190618_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='model_pic',
            new_name='recipe_image',
        ),
    ]
