# Generated by Django 2.2.2 on 2019-06-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20190618_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=35)),
                ('amount', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='Ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient'),
        ),
    ]
